version: '3.8'

services:
  ovietech-app:
    image: ovie2604/cicd-demo:latest
    container_name: ovietech-app
    ports:
      - "8082:8080"
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "ovietech-app:8080"
      - "--domain=overhung-dwindling-vivacious.ngrok-free.dev"
    depends_on:
      - ovietech-app
    restart: always